spring.application.name=smart-real-estate-advisor
server.port=8080

spring.datasource.url=jdbc:sqlite:${app.database.path}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always

app.database.path=data/advisor.db
app.ontology.path=src/main/resources/ontology/plovdiv-real-estate.owl
app.import.csv-path=src/main/resources/data/properties-plovdiv.csv
app.jade.platform-name=plovdiv-advisor
app.jade.main-host=localhost
app.jade.main-port=1099
